### ISSUE TITLE
Recommendation: Use a JSON library

### ISSUE THREAD

**Issue by fireduck64** [devrandom/java-stratum#1]
I like this one because it is very simple:
http://www.json.org/java/index.html

It seems like there is a good bit of hand built JSON strings, I'd recommend avoiding that.

**Comment by bauerj** [comment]
He's already using https://github.com/FasterXML/jackson .

I can only seem to find JSON-strings in the tests, which doesn't seem to be a bad idea.

**Comment by devrandom** [comment]
@fireduck64 I'm using Jackson - I've had very good experience with it.  The strings are all in the tests, as @bauerj says.

**Comment by fireduck64** [comment]
Cool
